POST http://localhost:8080/translate
Content-Type: application/json

{
  "text": "Ein Capybara ist gestern in einem Aufzug stecken geblieben.",
  "targetLanguages": [ "en_GB", "en_US", "fr", "es", "nl"]
}
