package polyglotter.ui

@Suppress("MayBeConst", "MagicNumber")
object UiConfig {
    val maxInputChars = 5_000
    val languages = listOf(
        Language("de"),
        Language("de", "AT"),
        Language("de", "CH"),
        Language("en"),
        Language("en", "GB"),
        Language("en", "US"),
        Language("es"),
        Language("fr"),
        Language("it"),
        Language("ja"),
        Language("zh"),
        Language("pl"),
        Language("pt"),
        Language("el"),
        Language("hu"),
        Language("is"),
        Language("sv"),
        Language("fi"),
        Language("no"),
        Language("ru"),
        Language("uk"),
        Language("da"),
        Language("nl"),
        Language("eo"),
        Language("af"),
        Language("ar"),
        Language("hy"),
        Language("bs"),
        Language("bg"),
        Language("ca"),
        Language("he"),
        Language("ht"),
        Language("hi"),
        Language("id"),
        Language("ga"),
        Language("ko"),
        Language("la"),
        Language("lb"),
        Language("sk"),
        Language("sl"),
        Language("th"),
        Language("tr"),
        Language("vi"),
        Language("cy"),
    ).sortedBy { it.displayName }
}
