logging:
  level:
    root: INFO
    polyglotter: DEBUG

spring:
  application:
    name: Polyglotter
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: gpt-4o
  threads:
    virtual:
      enabled: true
