logging:
  level:
    root: ${LOG_LEVEL_DEFAULT:info}
    polyglotter: ${LOG_LEVEL_APPLICATION:info}

server:
  error:
    includeMessage: always

spring:
  application:
    name: polyglotter
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        enabled: true
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o}
  threads:
    virtual:
      enabled: true
